package CommonUtils;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;


public class GeneratePOMClasses {

	public void generate(){
			BufferedReader bReader = null;
			try {
				
				String strLine;
				String strClassName=null;
				String strEleName;
				String strTesterName;
				boolean blnMentodEnd = false;
				
				bReader = new BufferedReader(new FileReader("src/test/java/elementRepository/element.properties"));
				
				while ((strLine = bReader.readLine()) != null) {
					
					if(strLine.contains("#Class-")){
						
						if(blnMentodEnd){
							FileWriter fw = new FileWriter(strClassName,true);
							BufferedWriter bw = new BufferedWriter(fw);
							bw.write("}");bw.newLine();
							bw.close();
							
						}
						
						blnMentodEnd=true;
						String[] strSplit = strLine.split("-");
						
						if(!strSplit[1].equalsIgnoreCase("end")){
							
								final String pagesPath = "temp/autoGeneratedCode/pages/";
								final String testerPath = "temp/autoGeneratedCode/tester/";
								strClassName = pagesPath + strSplit[1] + ".java";
								strTesterName = testerPath + strSplit[1] + "_tester.java";
								
								File p1 = new File(pagesPath);  
								File p2 = new File(testerPath);  
								
								if(!p1.exists()) {
									p1.mkdirs();
								}
								if(!p2.exists()) {
									p2.mkdirs();
								}
								p1 = null;
								p2=null;
								
								File file = new File(strClassName);
								File testerfile = new File(strTesterName);
				
								// if file doesn't exists, then create it
								if (file.exists()) {
									file.delete();
									file.createNewFile();
								}
								if (testerfile.exists()) {
									testerfile.delete();
									testerfile.createNewFile();
								}
								
								FileWriter fw = new FileWriter(strClassName,true);
								BufferedWriter bw = new BufferedWriter(fw);
								bw.write("package pageObject;");bw.newLine();
								bw.write("import org.openqa.selenium.WebElement;");bw.newLine();
								bw.write("import elementRepository.ElementFactory;");bw.newLine();
								bw.write("import utility.Log;");bw.newLine();
								bw.newLine();
								bw.write("public class " + strSplit[1] +"{");bw.newLine();
								bw.close();
								
								FileWriter fwt = new FileWriter(strTesterName,true);
								BufferedWriter bwt = new BufferedWriter(fwt);
								bwt.write("package tester;");bwt.newLine();
								bwt.write("import org.openqa.selenium.WebElement;");bwt.newLine();
								bwt.write("import elementRepository.ElementFactory;");bwt.newLine();
								bwt.write("import utility.Log;");bwt.newLine();
								bwt.write("import pages.*;");bwt.newLine();
								bwt.newLine();
								bwt.write("public class " + strSplit[1] +"_tester extends "+strSplit[1]+"{");bwt.newLine();
								bwt.write("}");
								bwt.close();
						}
					 }
					
					else{ 
						
					    String[] strSplit2 = strLine.split("=");
						strEleName = strSplit2[0];
						
						FileWriter fw = new FileWriter(strClassName,true);
						BufferedWriter bw = new BufferedWriter(fw);
						
						bw.write("   //Page object method for - "+strEleName);bw.newLine();
						bw.write("   public WebElement " + strEleName + "(){");bw.newLine();
						bw.write("     Log.info(\"Element Page Object >> "+strEleName+"\");");bw.newLine();
						bw.write("     return ElementFactory.getElement(\"" + strEleName + "\");");bw.newLine();
						bw.write("   }\n");bw.newLine();
						bw.close();
					
					}
					
				}
				
			} catch (Exception e) {
				e.printStackTrace();
			}finally {
				try {
					if (bReader != null)bReader.close();
				} catch (IOException ex) {
					ex.printStackTrace();
				}
			}	
	}
	
	public static void main(String[] a){
		GeneratePOMClasses genPOM = new GeneratePOMClasses();
		genPOM.generate();
		System.out.println("POM Generation Finished!!");
	}
}	